// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package transfer

import (
	"time"
)

type Transfer struct {
	ID int32
	// 收款金额
	Amount string
	// 付款人地址
	FromAddress string
	// 收款人地址
	ToAddress string
	// 区块
	Block int32
	// 哈希值
	TransactionID string
	// 确认时间
	Time time.Time
	// 更新时间
	UpdatedAt time.Time
	// 创建时间
	CreatedAt time.Time
}
