// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package transfer

import (
	"context"
	"time"
)

const createTransfer = `-- name: CreateTransfer :exec
INSERT INTO transfer
(amount,
 from_address,
 to_address,
 block,
 transaction_id,
 time,
 updated_at,
 created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTransferParams struct {
	Amount        string
	FromAddress   string
	ToAddress     string
	Block         int32
	TransactionID string
	Time          time.Time
	UpdatedAt     time.Time
	CreatedAt     time.Time
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) error {
	_, err := q.db.ExecContext(ctx, createTransfer,
		arg.Amount,
		arg.FromAddress,
		arg.ToAddress,
		arg.Block,
		arg.TransactionID,
		arg.Time,
		arg.UpdatedAt,
		arg.CreatedAt,
	)
	return err
}

const deleteTransfer = `-- name: DeleteTransfer :exec
DELETE
FROM transfer
WHERE transaction_id = ?
`

func (q *Queries) DeleteTransfer(ctx context.Context, transactionID string) error {
	_, err := q.db.ExecContext(ctx, deleteTransfer, transactionID)
	return err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, amount, from_address, to_address, block, transaction_id, time, updated_at, created_at
FROM transfer
WHERE transaction_id = ? LIMIT 1
`

func (q *Queries) GetTransfer(ctx context.Context, transactionID string) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransfer, transactionID)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.FromAddress,
		&i.ToAddress,
		&i.Block,
		&i.TransactionID,
		&i.Time,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const isExistTransfer = `-- name: IsExistTransfer :exec
SELECT EXISTS(SELECT 1 FROM transfer WHERE to_address = ? LIMIT 1)
`

func (q *Queries) IsExistTransfer(ctx context.Context, toAddress string) error {
	_, err := q.db.ExecContext(ctx, isExistTransfer, toAddress)
	return err
}

const transfer = `-- name: Transfer :one
SELECT id, amount, from_address, to_address, block, transaction_id, time, updated_at, created_at FROM transfer WHERE from_address = ? AND to_address = ? LIMIT 1
`

type TransferParams struct {
	FromAddress string
	ToAddress   string
}

func (q *Queries) Transfer(ctx context.Context, arg TransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, transfer, arg.FromAddress, arg.ToAddress)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.FromAddress,
		&i.ToAddress,
		&i.Block,
		&i.TransactionID,
		&i.Time,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
